baseURL = "https://doc.notapplicable.info"
languageCode = "en-us"
title = "Not Applicable Doc"
theme = "hugo-theme-learn"
publishDir = ".."

[params]
	themeVariant = "green"

[outputs]
	home = [ "HTML", "JSON"]
	page = [ "HTML"]
