baseURL = "https://marshyon.github.io"
#baseURL = "http://localhost:5500"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-learn"
publishDir = ".."

[outputs]
	home = [ "HTML", "JSON"]
	page = [ "HTML"]